services:

  web:
    image: php:8.3-apache
    container_name: athletics-web
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.4
    container_name: athletics-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: athletics
      MYSQL_USER: athletics
      MYSQL_PASSWORD: athletics
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: athletics-phpmyadmin
    platform: linux/amd64
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db

volumes:
  db-data: